### ISSUE TITLE
Minecraft.pricing

### ISSUE THREAD

**Issue by backfromhiatus** [interceptic/SkyblockValueParser#2]
Traceback (most recent call last):
  File "E:\0Skidders\listbot\start.py", line 3, in <module>
    from bot.bot import bot
  File "E:\0Skidders\listbot\bot\bot.py", line 3, in <module>
    from bot.modals.evalue import Embed
  File "E:\0Skidders\listbot\bot\modals\evalue.py", line 4, in <module>
    from minecraft.pricing.data_handler import user_stats, handle_stats
ModuleNotFoundError: No module named 'minecraft.pricing'

**Comment by interceptic** [comment]
did you augment any of the existing code?

**Comment by backfromhiatus** [comment]
no

**Comment by backfromhiatus** [comment]
Yo
