### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by Opencode101** [interceptic/SkyblockValueParser#3]
PS C:\Users\skibidi\Downloads\SkybotAIO-main (1)\SkybotAIO-main> python start.py
Traceback (most recent call last):
  File "C:\Users\skibidi\Downloads\SkybotAIO-main (1)\SkybotAIO-main\start.py", line 3, in <module>
    from bot.bot import bot
  File "C:\Users\skibidi\Downloads\SkybotAIO-main (1)\SkybotAIO-main\bot\bot.py", line 5, in <module>
    from bot.modals.list import Setup
  File "C:\Users\skibidi\Downloads\SkybotAIO-main (1)\SkybotAIO-main\bot\modals\list.py", line 5, in <module>
    from discord.ui import View, Button, InputText, Modal
ImportError: cannot import name 'InputText' from 'discord.ui' (C:\Users\skibidi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ui\__init__.py)
PS C:\Users\skibidi\Downloads\SkybotAIO-main (1)\SkybotAIO-main>

this is with the latest update too

**Comment by interceptic** [comment]
This issue is caused by not up to date py-cord installation, type pip uninstall py-cord, then pip install --upgrade py-cord

**Comment by Opencode101** [comment]
what about the open ai key, where do i set that

**Comment by interceptic** [comment]
https://platform.openai.com/docs/overview

Note that using openai isn't required for the bot to function
